### ISSUE TITLE
Gatsby build fails if content returned from Strapi is NULL

### ISSUE THREAD

**Issue by Borisboky** [gatsby-uc/gatsby-source-strapi#107]
I'm using `"gatsby": "2.18.4"` and `"gatsby-source-strapi": "0.0.10"`.

The problem is that Gatsby build fails if the returned content is NULL. There are a few hacks, for example adding dummy data to every field, but that is not how it should be.

I have a big amount of content-types an dI do not want to add for every content type dummy data.

I have component where there can be 12 images, 12 titles, 12 descriptions, .... And if want to show only one, I need to add the other 11 images, titles, descriptions.

Any idea when will that be fixed?

**Comment by alehuo** [comment]
Same issue, `"gatsby": "^2.19.23"` and `"gatsby-source-strapi": "0.0.10"`

**Comment by Borisboky** [comment]
@alehuo That is BIG issue and nobody does anything. Nobody cares.

There are a few similar questions, but there is no solution.

**Comment by tomolenet** [comment]
As far as I know there will be a new gatsby strapi source plugin available in near future.

**Comment by kyuumeitai** [comment]
@Borisboky This is true for strapi and for **all the gatsby data plugins**, not only Strapi. It's not Strapi's fault. The official gatsby response is that you have to make sure that you have at least one field to avoid non-existant nodes in Graphql.

The thing that you're mentioning though doesn't make sense: did you use a repeater/array component? how the structure in your API is seeing, as an array, right? if that's the case, you only need 1 photo field/description.

Maybe if you post the structure we can help you.

**Comment by kyuumeitai** [comment]
btw, I'm moving to Strapi+Next.js because this very issue.

**Comment by denforlatte** [comment]
I got around this issue by explicitly writing some of the schema for parts of my Strapi content that are optional, as per this documentation:
https://www.gatsbyjs.org/docs/schema-customization/

Not a perfect fix, but I thought I would share it anyway in case it helps someone.

**Comment by ballPointPenguin** [comment]
This issue is very frustrating. For this and other reasons I recommend replacing gatsby-source-strapi with gatsby-source-graphql. So far it's a much better experience and totally fine with NULL values. I'm not sure what gatsby-source-strapi is supposed to provide that I can't do with gatsby-source-graphql. This does not seem like a production-ready plugin yet.

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or join us on [Discord](https://discord.gg/Qy2rwbHbwN) if you have questions!
