### ISSUE TITLE
Generate Gatsby's GraphQL schema based on Model instead of REST API result

### ISSUE THREAD

**Issue by yagotome** [gatsby-uc/gatsby-source-strapi#128]
Is it possible this plugin generate Gatsby's GraphQL schema based on Model instead of REST API result?

The problem is if there's `null` fields in the results, the Gatsby's schema is compromised. What if this plugin support an option to fetch from [Strapi's GraphQL schema](https://github.com/strapi/strapi/tree/master/packages/strapi-plugin-graphql)?

**Comment by Jaikant** [comment]
@yagotome There seems to be more than one issue by using the REST API. See this [issue](https://github.com/strapi/gatsby-source-strapi/issues/127#issuecomment-630783922)

**Comment by yagotome** [comment]
@Jaikant good catch! I've also reported similar problem [here](https://github.com/strapi/strapi/discussions/6242).

**Comment by jblevins1991** [comment]
I wouldn't say this is so much an issue, but a limitation of using REST in general. It seems that using the GraphQL plugin removes this limitation. I think it's safe to say that Strapi should probably just move to using GraphQL, as none of its users will notice a difference until they hit this limitation. It's all stuff abstracted from developers that aren't working directly on Strapi code.

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or join us on [Discord](https://discord.gg/Qy2rwbHbwN) if you have questions!
