### ISSUE TITLE
Sort by object Field using graphql

### ISSUE THREAD

**Issue by kmandina** [gatsby-uc/gatsby-source-strapi#129]
I have this query
query ProdType{
  type{
    id
    products(sort: "general.order:asc"){
        id
        name
        description
        general{
          order
          visibility
        }
    }
  }
}

I want to sort by order but this field is from General and the query didn´t work 
What can i do?

**Comment by paul-ebose** [comment]
you can use graphiql to prototype your queries

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or join us on [Discord](https://discord.gg/Qy2rwbHbwN) if you have questions!
