### ISSUE TITLE
pngquant pre-buuild test failed

### ISSUE THREAD

**Issue by kautilyshubham** [gatsby-uc/gatsby-source-strapi#132]
![image](https://user-images.githubusercontent.com/40838099/84578368-2731a300-ade2-11ea-9e8b-c3d231b12f30.png)

**Comment by endymion1818** [comment]
I think this is a known issue with pngquant on Windows and not necessarily an issue with Strapi's plugin (or Strapi itself): https://github.com/gruntjs/grunt-contrib-imagemin/issues/96#issuecomment-42759424 && https://github.com/gatsbyjs/gatsby/issues/4866

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or join us on [Discord](https://discord.gg/Qy2rwbHbwN) if you have questions!
