### ISSUE TITLE
Fetching data takes 10 mins

### ISSUE THREAD

**Issue by munwr** [gatsby-uc/gatsby-source-strapi#152]
Hi @lauriejim,

As per our conversation on twitter via stackrole, am creating this issue.

## Context
we have around 72 posts with 2 images each. Am suspecting parsing this info is taking a lot of time.

Local: 480s 
Production: 58s

We do not have a filter on relations, but on the content type field Status

```graphql
allStrapixxxx (
    sort: {order: DESC, fields: date}, 
    filter: {Status: {eq: "published"}}
) {
  Image {
    childImageSharp {
       fluid(maxWidth: 416, srcSetBreakpoints: [832]) {
         ...GatsbyImageSharpFluid_withWebp_tracedSVG
       }
    }
  }
}
```

Thank you, looking forward to hearing from you :)

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or join us on [Discord](https://discord.gg/Qy2rwbHbwN) if you have questions!
