### ISSUE TITLE
My data appears in the playground query, but when I check the route, the data becomes an integer

### ISSUE THREAD

**Issue by felipevc13** [gatsby-uc/gatsby-source-strapi#169]
My data appears in the playground query, but when I check the route, the data becomes an integer.
Is this a bug or some configuration that I don’t know how to do?
![strapi-route](https://user-images.githubusercontent.com/25945473/103284855-2c8bbf00-49bb-11eb-834b-79aace203481.jpg)
![strapi-playground](https://user-images.githubusercontent.com/25945473/103284857-301f4600-49bb-11eb-84d3-eb483be884eb.jpg)

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or join us on [Discord](https://discord.gg/Qy2rwbHbwN) if you have questions!
