### ISSUE TITLE
Cut a new alpha release after bumping axios to 0.21.1?

### ISSUE THREAD

**Issue by collinwu** [gatsby-uc/gatsby-source-strapi#179]
Hello maintainers,

I've been leveraging `"gatsby-source-strapi": "^1.0.0-alpha.0"` for a few months now.

`npm install --save gatsby-source-strapi@alpha` installs the above version that doesn't address the vulnerable axios version.

can you bump / cut a new alpha release to address the advisory?

https://www.npmjs.com/advisories/1594

Please advise

**Comment by jdortegar** [comment]
+1

**Comment by mrmikardo** [comment]
I am also affected by this issue.

Please let me know if I can help out in any way! :)

**Comment by mrmikardo** [comment]
Hey there, is there any update on this issue? It still seems to be affecting me.

Thanks!

**Comment by jdortegar** [comment]
We still waiting for this :(

**Comment by collinwu** [comment]
👀

**Comment by jdortegar** [comment]
@collinwu this is fixed in the last alpha version
https://github.com/strapi/gatsby-source-strapi/compare/v1.0.0-alpha.0...v1.0.0-alpha.1#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R45

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or join us on [Discord](https://discord.gg/Qy2rwbHbwN) if you have questions!
