### ISSUE TITLE
Question: Making realtime queries

### ISSUE THREAD

**Issue by ottogutierrez** [gatsby-uc/gatsby-source-strapi#180]
Hello,

I would like to know if it is possible to use this library on Gatsby to make real time queries.

Since this plugin already knows the information of my strapi API, I'm wondering if creation a wrapRootElement (Gatsby ssr API) I can just setup a normal query and just get real time data when the page loads.

Thank you!

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or join us on [Discord](https://discord.gg/Qy2rwbHbwN) if you have questions!
