### ISSUE TITLE
Gatsby not showing images

### ISSUE THREAD

**Issue by dorandegraeve** [gatsby-uc/gatsby-source-strapi#181]
I cant show images that i get with graphql from the dynamic zone.

![image](https://user-images.githubusercontent.com/29143272/109307402-e0d18680-7840-11eb-9dd0-9560ea15247b.png)
![image](https://user-images.githubusercontent.com/29143272/109307435-f0e96600-7840-11eb-89d6-1e6800dee565.png)
![image](https://user-images.githubusercontent.com/29143272/109307620-35750180-7841-11eb-9ff6-4f18ca2c3602.png)

I get all the data as you can see in the console.log. But when i try to display it, it shows an error.

![image](https://user-images.githubusercontent.com/29143272/109308003-c055fc00-7841-11eb-99f4-232b66711981.png)

I hope someone can help me quickly. as i am desperate

**Comment by Mites88** [comment]
use ``...GatsbyImageSharp`` instead of ``src`` in your query

and when calling the image, use just ``content.CardImage.childImageShar.fluid``

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or join us on [Discord](https://discord.gg/Qy2rwbHbwN) if you have questions!
