### ISSUE TITLE
_locale field is not present once project is built

### ISSUE THREAD

**Issue by LiamDotPro** [gatsby-uc/gatsby-source-strapi#187]
Currently the i18n soloution uses `_locale` to filter by locale's but this is being rewritten to locale which I believe to be being stripped from inside `fetch.js` maybe I'm wrong? If someone can provide some clarity about the right place to look I don't mind making the changes so we can try out the i18n beta with gatsby.

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or join us on [Discord](https://discord.gg/Qy2rwbHbwN) if you have questions!
