### ISSUE TITLE
suggest collectionTypes/singleTypes can set a async/await function

### ISSUE THREAD

**Issue by zsrl** [gatsby-uc/gatsby-source-strapi#244]
Because I have a lot of data, I want to classify and query the data, but there are also a lot of classifications. I need to take the classifications from the database and mark the ID of each classification respectively. Therefore, I think I need a async/await function here.

```
{
  resolve: "gatsby-source-strapi",
  options: {
    apiURL: "http://localhost:1337",
    collectionTypes: async () => {
      reurn await myFetchFunc()  // fetching data
    },
    queryLimit: 1000,
  }
}
```

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or join us on [Discord](https://discord.gg/Qy2rwbHbwN) if you have questions!
