### ISSUE TITLE
Failed to resolve gatsby-scource-strapi unreachable

### ISSUE THREAD

**Issue by RavinduHarshana** [gatsby-uc/gatsby-source-strapi#255]
There was a problem loading plugin "gatsby-scource-strapi". Perhaps you need to install its package?
Use --verbose to see actual error.

**Comment by Notaduck** [comment]
Try to give us some more info. 

Is `gatsby-scource-strapi` in your `package.json`? And how does your `gatsby-config.js` file look like?

**Comment by slant** [comment]
Could the issue be that you're using `gatsby-scource-strapi` (`sCource`) instead of `gatsby-source-strapi`?
