### ISSUE TITLE
Gatsby develop hangs for minutes on "Source and Transform Nodes"

### ISSUE THREAD

**Issue by ZeldOcarina** [gatsby-uc/gatsby-source-strapi#327]
I am developing a new Gatsby app with Strapi.
It takes a looong time to source data, 5 minutes or more for every development cycles, sometimes it just hangs forever.
I've set the Strapi instance to production and it seems to work well.
I've checked the Strapi server and it's not hung or anything!

Do you have any ideas?

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or join us on [Discord](discord.gg/gwnqfzetjv) if you have questions!
