### ISSUE TITLE
Plugin doesn't update data when content on admin changes

### ISSUE THREAD

**Issue by denisgoryaynov** [gatsby-uc/gatsby-source-strapi#331]
When changing data on the admin panel the plugin doesn't update the data on the frontend even if the api response contains the correct data.
From the console I can see that two queries are made:

the first one fetches all content types and if I do the same request with postman I can see that the content is updated:
```
info Starting to fetch data from Strapi - /api/projects with
{"pagination":{"pageSize":250,"page":1},"populate":"*","locale":"en"}
```

the second request starts from page 2 and returns an empty array:
```
info Starting to fetch data from Strapi - /api/projects with
{"pagination":{"pageSize":250,"page":2},"populate":"*","filters":{"updatedAt":{"
$gt":1656407094198}},"locale":"en"}
```

If I do the same request with postman but set the `page` parameter to 1 I get an array with the element(s) that were updated since the last gatsby build.

It seems that the newOrExistingEntries is not populated correctly at this line https://github.com/strapi/gatsby-source-strapi/blob/48fa72d8f20a1d8cf168db34015397a368faacd9/src/gatsby-node.js#L93

Edit: setting `maxLimit: 500,` inside config/plugins.ts on the admin panel seems to fix the issue. Right now we have 159 projects on our backend, maybe the issue has to do with the fact that by default strapi has a maxLimit of 100 and it messes up with the pagination from the plugin?

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or join us on [Discord](discord.gg/gwnqfzetjv) if you have questions!
