### ISSUE TITLE
Error: EPERM: operation not permitted, lstat

### ISSUE THREAD

**Issue by Hasnain-110** [gatsby-uc/gatsby-source-strapi#332]
"gatsby-source-strapi": "^1.0.2",

![image](https://user-images.githubusercontent.com/81685621/177931819-29fadf9e-dece-46dd-a8e6-bcf0c13180b2.png)

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or join us on [Discord](discord.gg/gwnqfzetjv) if you have questions!
