### ISSUE TITLE
How to fetch custom API

### ISSUE THREAD

**Issue by tansongchen** [gatsby-uc/gatsby-source-strapi#339]
I am trying to use a Strapi plugin [Navigation](https://www.npmjs.com/package/strapi-plugin-navigation) which provides API like this:

```
GET https://<host>/api/navigation/render/1
```

which did not happen to be the standard collection / single type API routes. How may I use this in Gatsby?

**Comment by rroslaniec** [comment]
Same problem here 👋

**Comment by raae** [comment]
I am no Strapi expert, but you can always source content from an API endpoint yourself using the `sourceNodes` lifecycle hook. You might get an idea from my post showing two ways of [paginate through API results when sourcing data In Gatsby](https://queen.raae.codes/emails/2022-05-27-pagination/).

**Comment by rroslaniec** [comment]
yea, @raae you're right. But in the previous version that was possible :( Now I need to have time to refactor it...

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or join us on [Discord](discord.gg/gwnqfzetjv) if you have questions!
