### ISSUE TITLE
Single Types don't update on rebuild if multiple locales exist

### ISSUE THREAD

**Issue by MRDRMUFN** [gatsby-uc/gatsby-source-strapi#341]
It appears if a second language version is saved for a `Single Type` the node will not show saved changes on rebuild in any fields.

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or join us on [Discord](discord.gg/gwnqfzetjv) if you have questions!
