### ISSUE TITLE
Image Processing in HTML code

### ISSUE THREAD

**Issue by AliceRossa** [gatsby-uc/gatsby-source-strapi#346]
I'm trying to use the "CKEditor 5 for Strapi" plugin but I can't seem to use Gatsby's image processing for images in HTML code.

```
{
  "data": {
    "strapiHomepage": {
      "content": {
        "data": {
          "content": "<h1>Homepage</h1><p><img src=\"/uploads/image1.jpg\" alt=\"image1.jpg\"> <src=\"/uploads/image2.jpg\" alt=\"image2.jpg\"></p><p>Welcome on my homepage</p>"
        }
      }
    }
  }
}
```

I tried to add the code below in gatsby-config.js but without success.
```
singularName: `homepage`,
queryParams: {
  content: {
    data: {
      populate: {
        content: "*",
      },
    },
  }
}
```
The only solution found is to add Strapi's api url as a prefix to the images' url, but this is not the solution sought.
Is there a particular configuration for processing images from HTML code? Thanks

**Comment by cuca-marko** [comment]
I was wondering the same thing. Can anyone shine some light on this?

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or join us on [Discord](discord.gg/gwnqfzetjv) if you have questions!
