### ISSUE TITLE
Plugin is not pulling data from Strapi when there is a timestamp on the cache.

### ISSUE THREAD

**Issue by eeni** [gatsby-uc/gatsby-source-strapi#347]
https://github.com/strapi/gatsby-source-strapi/blob/88d1fd57320bf89ee3b068a14f637aae770ed7a8/src/gatsby-node.js#L104

So I am having this issue when I run my app and the cache does have a value for the `gatsby-source-strapi` plugin.
The response returned from Strapi when a request with the `updatedAt` param is
 `{
    "data": null,
    "error": {
        "status": 404,
        "name": "NotFoundError",
        "message": "Not Found",
        "details": {}
    }
}`.

In that scenario the `newOrExistingEntries` would be `[ [] ]` and the expression `const data = newOrExistingEntries  || allResults;`
will assign `data` a value of `[ [] ]`, and this consists on not pulling any data from Strapi.

I think there must be a deep check for the existence of `newOrExistingEntries` when evaluating the value of `data` to except this case of `newOrExistingEntries` that passes the JS conversion to Boolean with the value `[[]]`.

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or join us on [Discord](discord.gg/gwnqfzetjv) if you have questions!
