### ISSUE TITLE
CreateTypes Camel case vs. snake case

### ISSUE THREAD

**Issue by Rodrigo127** [gatsby-uc/gatsby-source-strapi#351]
Is it necessary to use SnakeCase when using the action **createTypes**?

> type STRAPI_AUTO_CALCULATOR_STATE implements Node {
>   about_author: STRAPI_AUTO_CALCULATOR_STATEAbout_author
> }

Next one with camel case didn't work (also tried with @dontInfer).

> type StrapiAutoCalculatorState implements Node {
>   about_author: STRAPI_AUTO_CALCULATOR_STATEAbout_author
> }

This is the type when using the playground:
![image](https://user-images.githubusercontent.com/40726965/198904461-310883fd-587e-4b25-81ae-fae957ededf4.png)

The typeDefs.gql contains both definitions **StrapiAutoCalculatorState** and **STRAPI_AUTO_CALCULATOR_STATE**

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or join us on [Discord](discord.gg/gwnqfzetjv) if you have questions!
