### ISSUE TITLE
Getting "Unknown type" for the starter project

### ISSUE THREAD

**Issue by pratclot** [gatsby-uc/gatsby-source-strapi#353]
Hey everyone.

I am using a fresh `gatsby-blog` starter project, and receive this error when I remove a component from a dynamic zone on the `About` page (I want a simple page with only richText in the end):
```
success onPostBootstrap - 0.003s
info bootstrap finished - 6.233s
success onPreExtractQueries - 0.001s

 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "STRAPI__COMPONENT_SHARED_MEDIASTRAPI__COMPONENT_SHARED_QUOTESTRAPI__COMPONENT_SHA
RED_RICH_TEXTSTRAPI__COMPONENT_SHARED_SLIDERUnion". Did you mean "STRAPI__COMPONENT_SHARED_MEDI
ASTRAPI__COMPONENT_SHARED_QUOTESTRAPI__COMPONENT_SHARED_RICH_TEXTUnion"?

GraphQL request:2:22
2 |   fragment Blocks on STRAPI__COMPONENT_SHARED_MEDIASTRAPI__COMPONENT_SHARED_QUOT
  |                      ^
  | ESTRAPI__COMPONENT_SHARED_RICH_TEXTSTRAPI__COMPONENT_SHARED_SLIDERUnion {

File: src/templates/article-post.js:37:22
```

When I export the schema from Strapi I see these two entries:
```
union AboutBlocksDynamicZone =
    ComponentSharedMedia
  | ComponentSharedQuote
  | ComponentSharedRichText
  | Error

union ArticleBlocksDynamicZone =
    ComponentSharedMedia
  | ComponentSharedQuote
  | ComponentSharedRichText
  | ComponentSharedSlider
  | Error
```

My `gatsby-config.js` is identical to the [stock](https://github.com/strapi/starters-and-templates/blob/main/packages/starters/gatsby-blog/starter/gatsby-config.js) one.

I also inlined the `Blocks` fragment in `about.js`, just to make sure this fragment is referenced only by `article-post.js`.

Can you please help me understand why the union type is not visible for Gatsby?

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or join us on [Discord](discord.gg/gwnqfzetjv) if you have questions!
