### ISSUE TITLE
Cannot retrieve sub-components of components in graphql?

### ISSUE THREAD

**Issue by LiamWinterton** [gatsby-uc/gatsby-source-strapi#354]
I have a basic component called SEO, that I have added to a collection called post(s).

Inside this SEO component I also have another component called image, which contains an image field and a text field for specifying alt text. I added this under the key sharedImage

In the admin, I can create a post just fine, and populate all this data. In the gatsby graphql playground, I can obtain my posts, my direct SEO data fields ( metaTitle, metaDescription ) but sharedImage is no-where to be found.

I've cleared gatsby cache with gatsby clean and restarted both strapi and gatsby 10's of times now, and this data is simply not populating. Is there a known issue / limitation with this?

**Comment by LiamWinterton** [comment]
> Hi Liam,
> 
> Did you deep populate the images in your gatsby-config.js?
> 
> Like so, in the gatsby-source-strapi plugin in gatsby-config.js:
> 
> `... populate: { sharedImage: "*", Testimonial: { populate: "*", }, ...` Save and restart Gatsby. Hope it helps.
> 
> Cheers, Jacco

Using both:

```js
queryParams: {
    populate: {
        seo: {
            socialImage: "*"
        }
    }
}
```

```js
queryParams: {
    populate: {
        seo: {
            socialImage: {
                populate: "*"
	    }
        }
    }
}
```

and: 

Removes all the socialimage field from my graphql entirely. (I changed the name from shareImage to socialImage in hopes of kicking it up the arse a bit.

**Comment by LiamWinterton** [comment]
@bureauberg This seems to only be an issue with the fact that my image is a sub component. If I remove the component and add an image field directly to the seo component it works perfectly fine.

**Comment by laurenskling** [comment]
Have you tried:

```
queryParams: {
    populate: {
        seo: {
          populate: {
            socialImage: "*"
          }
       }
    }
}
```

**Comment by laurenskling** [comment]
It is possible. I have components in components in DZ's. Its just mind boggling to write the populate queries...

You can try to "debug" it by calling the REST API yourself with the populate fields. You can see what endpoint is being called by Gatsby when you run develop. Copy/Paste that URL and try to change it to work.

**Comment by laurenskling** [comment]
Maybe it's this:

```
queryParams: {
    populate: {
        // probably you need to put `image: *` here as well if you have an image directly on the post. The default `populate: *` gets removed by using this feature
        seo: {
          populate: 'socialImage'
       }
    }
}
```

**Comment by LiamWinterton** [comment]
> Maybe it's this:
> 
> ```
> queryParams: {
>     populate: {
>         // probably you need to put `image: *` here as well if you have an image directly on the post. The default `populate: *` gets removed by using this feature
>         seo: {
>           populate: 'socialImage'
>        }
>     }
> }
> ```

populate: "socialImage" appears to be the solution.

Do you mind sharing how you came to this conclusion, because I couldn't find anything about this in the docs?

**Comment by laurenskling** [comment]
Thats a very good question...
I guess I just fiddled around long enough with all the options laid out in: 
https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/populating-fields.html#relation-media-fields
and
https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/populating-fields.html#component-dynamic-zones

it's a hot mess to get the correct combination going.

**Comment by charanjit-singh** [comment]
Huff finally: https://market.strapi.io/plugins/strapi-plugin-populate-deep

**Comment by LiamWinterton** [comment]
Unfortunately we've since moved to sanity!

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or join us on [Discord](discord.gg/gwnqfzetjv) if you have questions!
