### ISSUE TITLE
GatsbyImageData in dynamic zones

### ISSUE THREAD

**Issue by LiamWinterton** [gatsby-uc/gatsby-source-strapi#356]
I am closing this PR as DZ are now supported in the new version.

_Originally posted by @soupette in https://github.com/strapi/gatsby-source-strapi/issues/248#issuecomment-1042762574_

This appears to be broken for me again. Using v2.0.0

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or join us on [Discord](discord.gg/gwnqfzetjv) if you have questions!
