### ISSUE TITLE
Gatsby GraphQL validation error - '"id" must be a string'

### ISSUE THREAD

**Issue by zdhz** [gatsby-uc/gatsby-source-strapi#6]
Hi,

I'm not sure which repo this ticket belongs in, but I've just installed `strapi`, `gatsby` and `gatsby-source-strapi` and I'm blocked by the following validation error.

### Error:
```
...

⠁ Starting to fetch data from Strapi (blog)
Fetch Strapi data: 22.840ms
The new node didn't pass validation
ValidationError: child "id" fails because ["id" must be a string]

...

warning The gatsby-source-strapi plugin has generated no Gatsby nodes. Do you need it?

...
```

### JSON
```
{  
   title:'My first blog post',
   subtitle:'This is a subtitle',
   body:'# Title\r\n\r\nlorem ipsum\r\n\r\n## Title 2\r\n\r\n',
   created_at:'2018-05-16T15:16:19.000Z',
   updated_at:'2018-05-16T15:16:19.000Z',
   image:{  
      id:1,
      name:'placeholder@2x.png',
      hash:'e419ebab4a704411a936081995bcbe75',
      ext:'.png',
      mime:'image/png',
      size:'8.22',
      url:'/uploads/e419ebab4a704411a936081995bcbe75.png',
      provider:'local',
      created_at:'2018-05-16T15:16:19.000Z',
      updated_at:'2018-05-16T15:16:19.000Z'
   },
   strapiId:1,
   id:1,
   parent:'__SOURCE__',
   children:[  

   ],
   internal:{  
      type:'StrapiBlog',
      contentDigest:'56bc67586b1ac07cefce2e9e84028095',
      owner:'gatsby-source-strapi'
   }
}
```

#### Versions

    "gatsby": "^1.9.247",
    "gatsby-source-strapi": "^0.0.3",

    "strapi": "3.0.0-alpha.12.1.3",

#### Related
[gatsby#5310](https://github.com/gatsbyjs/gatsby/issues/5310)

---

Please let me know if you need any more information.

FYI I'm not too familiar with the Gatsby API but I'd be happy to have a go at fixing this issue if anyone could point me in the right direction. 

Thanks in advance.

**Comment by gillesdm** [comment]
I'm also having the exact same issue. Followed the Gatsby & Strapi tutorial up until the point where I create the index page. Permissions in strapi have been set to the enable "find". (I believe the Guest role has become "Public" instead? This is where I enabled the user find and articles find).

**Comment by ladeiko** [comment]
Add tom package.json scripts

"postinstall": "ruby -pi -e \"gsub(/^(\\s+)return clean\\(item\\);/,'\\1item.id=item.id.toString();return clean(item);')\"  ./node_modules/gatsby-source-strapi/fetch.js"

**Comment by Caffeineli** [comment]
@ladeiko thanks for this. I hope they look at patching this soon.

**Comment by ntloi95** [comment]
> Add to package.json scripts
> 
> ```
> "postinstall": "ruby -pi -e \"gsub(/^(\\s+)return clean\\(item\\);/,'\\1item.id=item.id.toString();return clean(item);')\"  ./node_modules/gatsby-source-strapi/fetch.js"
> ```

Could you explain what happened?
