### ISSUE TITLE
error (node:68661) Warning: No such label 'Fetch Strapi data' for

### ISSUE THREAD

**Issue by davidkartuzinski** [gatsby-uc/gatsby-source-strapi#65]
**Describe the bug**

After installing the gatsby-source-strapi plugin, and when we run Gatsby we get the following error:

error (node:68661) Warning: No such label 'Fetch Strapi data' for

**Steps to reproduce the behavior**

Install gatsby-soruce-strapi
create a content-type
create a template
query the graph with a graphql query 
display the data.

**Expected behavior**

to display the data without console error.  The data is displayed but we get errors.

**System**

Latest versions of Gatsby
Latest Beta and Alpha versions of Strapi

**Additional context**

The error seems to be coming from this file:

https://github.com/strapi/gatsby-source-strapi/blob/master/src/fetch.js

**Comment by mjurincic** [comment]
Same problem with  gatsby-soruce-strapi is this just false positive error since content gets fetched or there is really a bug

**Comment by davidkartuzinski** [comment]
@mjurincic - This is a false positive error.  The data DOES get fetched.

**Comment by luck2011** [comment]
Same here! The `No such label` error message from `console.timeEnd` method locates in NodeJS [this line](https://github.com/nodejs/node-v0.x-archive/blob/master/lib/console.js#L87)

**Comment by luck2011** [comment]
#59 fixed this issue.

![56810201-5ed83700-683e-11e9-813b-5499777b70f5](https://user-images.githubusercontent.com/1066610/61675700-f65d0100-ad2b-11e9-905e-ab3dc91f3c39.png)

Eg. we make 4 requests. The `console.time` has the same key `Fetch Strapi data` for each request, when the first request finishes, it resolves the `Fetch Strapi data` key.  So the `console.timeEnd` in the following 3 requests run into the `No such label` error.

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or join us on [Discord](https://discord.gg/Qy2rwbHbwN) if you have questions!
