### ISSUE TITLE
Find an additional official maintainer for `gatsby-source-strapi` plugin

### ISSUE THREAD

**Issue by davidkartuzinski** [gatsby-uc/gatsby-source-strapi#68]
Gatsby and Strapi play very nicely together.  In fact, Strapi is the logical choice for individuals and companies who need a secure, open-source and customizable headless CMS along-side the front-end benefits that Gatsby offers.

In parallel to the work being performed by the Strapi Core team and the many Strapi community members who contribute to code, documentation, and issues. The official plugins also need to be maintained and improved upon. Due to time constraints, we are searching for community members to help us by becoming official maintainers to the plugin.

We welcome contributions from anyone in the community who sees a way to improve the product, but if you have experience using Strapi with Gatsby and see a vision on how to integrate and improve it, please reach out if you'd like to be part of the official core maintainers?

**Comment by henrych4** [comment]
Any requirement for being an official core maintainer? I have been using strapi together with gatsby for a while and would like to contribute to the community.

**Comment by davidkartuzinski** [comment]
The only requirements are really to have sufficient experience using both Gatsby & Strapi together, the ability to make pull requests on the plugin (technically), and/or have a vision of what the plugin could become and/or willing to help improve/maintain the docs/tutorial at Strapi and/or Gatsby.js (eventually).

Any interest in helping to create a starter theme would also be welcome.    

The reality is that Strapi fills a big space for Gatsby users and we would like to provide them with the best experience possible when using Strapi.

**Note:** The current Gatsby/Strapi tutorial will eventually be moved to the docs and completely rewritten. 

Would you like to find me in the [Strapi Slack Channel](slack.strapi.io)?
