### ISSUE TITLE
User friendly error messages upon api failures

### ISSUE THREAD

**Issue by Naismith** [gatsby-uc/gatsby-source-strapi#70]
We should add user friendly error messages upon api failures - such as a 403 and mentioning how to edit permissions for content types.

**Comment by davidkartuzinski** [comment]
@Aurelsicoko @lauriejim - @Naismith has a good point. I have thought about this as well.  Maybe this can be a community driven event "Add beautiful informative error messages" CALL TO ACTION?

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or join us on [Discord](https://discord.gg/Qy2rwbHbwN) if you have questions!
