### ISSUE TITLE
gatsby-source-strapi does not replace all nodes using ENABLE GATSBY REFRESH ENDPOINT from gatsby

### ISSUE THREAD

**Issue by jlfalcon3589** [gatsby-uc/gatsby-source-strapi#75]
Hello, I would like to see if you could help me with the following problem, I added the isuue in gatsby, but I think the problem is with the strapi plugins, sorry if this is not the space or to link to another project is that I did not want to repeat the same is here.

https://github.com/gatsbyjs/gatsby/issues/15740

**Comment by davidkartuzinski** [comment]
@jlfalcon3589 Thank you for bringing this issue up. This does seem to be the correct place to leave an issue about this. 

From what I understand, you are deleting content from your Strapi Admin area, but it is not being deleted "really" and still showing up on your gatsby site?

Could you tell us what database you're using and where you're hosting Strapi?

**Comment by puzzledbytheweb** [comment]
Hello! I am having a similar issue when adding content. I add some entries of my content type but, even though it is being added to the database (MongoDB) Gatsby isn't getting these new entries.

Is it possible that there is some kind of caching happening at the plugin level?

Thanks in advance ;)

**Comment by davidkartuzinski** [comment]
@puzzledbytheweb - 

> Is it possible that there is some kind of caching happening at the plugin level?

Not exactly.  You will need to rebuild your gatsby site each time you add or change content.  Did you follow the tutorial and create a webhook to automatically build it when you add more content?

**Comment by jlfalcon3589** [comment]
> @jlfalcon3589 Thank you for bringing this issue up. This does seem to be the correct place to leave an issue about this.
> 
> From what I understand, you are deleting content from your Strapi Admin area, but it is not being deleted "really" and still showing up on your gatsby site?
> 
> Could you tell us what database you're using and where you're hosting Strapi?

I am using strapi integration with mongodb

**Comment by puzzledbytheweb** [comment]
@davidkartuzinski Thanks. I probably skipped that part or configured it wrongly.

**Comment by davidkartuzinski** [comment]
@jlfalcon3589 - I am having trouble understanding the full context of this issue.  Could you please provide the full context following the issue template:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.


```

**Comment by DekiGk** [comment]
@jlfalcon3589 This works. Please check this comment:
https://github.com/strapi/strapi/issues/1443#issuecomment-578459637

You just need to make a `POST` request once you open this endpoint in Gatsby and it gets updated

**Comment by DekiGk** [comment]
Has anyone found a way to do this in staging and production without triggering a Gatsby rebuild/redeploy?

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or join us on [Discord](https://discord.gg/Qy2rwbHbwN) if you have questions!
