### ISSUE TITLE
cannot fetch empty fields

### ISSUE THREAD

**Issue by deebov** [gatsby-uc/gatsby-source-strapi#86]
Hi there 

Gatsby fails to build the project if I try to fetch an empty field from Strapi.  e.g. I have the Post content type  in Strapi but it does not contain any post. So, when I try to fetch `allStrapiPost` it throws an error during the build process. 

The error message:
![image](https://user-images.githubusercontent.com/28673719/68104452-e9d86f00-fefc-11e9-8ffa-49d0e847d247.png)

P.s. I would really appreciate if someone could help solving this issue 🙏

**Comment by masives** [comment]
Error suggests that you're querying allStrapiPosition, I'm confused. Also did you change public user permision so it can actually be read?

**Comment by hugomallet** [comment]
same here

**Comment by rozpuszczalny** [comment]
I'm facing same issue. Currently I have to create dummy-content just to make sure that every GraphQL type is created properly, just to bypass this problem.

I've seen an API for quering content types in Strapi (it was `/content-manager/content-types` and `/content-manager/groups`), it may solve this problem, because we would be able to query correct types, but with no results. But a PR for this would be required, since it changes how `gatsby-source-strapi` works now.

**Comment by waynehaffenden** [comment]
@rozpuszczalny Thank you for this, what did you use for image/file types? Especially, that I'm using fluid images in Gatsby, thank you.

**Comment by rozpuszczalny** [comment]
@waynehaffenden 
I haven't used gatsby with images. However, you can go to `/__graphql` playground, click in the upper right corner on "Docs >", and then type in a name of the type. See attached screenshot:
![search-by-time-name](https://user-images.githubusercontent.com/7627635/86408320-12488100-bcb7-11ea-8e62-26eab37debbf.png)

**Comment by waynehaffenden** [comment]
@rozpuszczalny Thank you

**Comment by kjoscha** [comment]
To prevent errors dealing with content-types without existing records, just use the `gatsby-plugin-schema-snapshot` plugin. Set the "update" option to "true" and build your app with all content-types having at least one record (e.g. a dummy record). That creates a `schema.gql` file in the root of your app folder. Afterwards, set the plugin's "update" option to "false" and remove your dummy record. No complaints anymore while gatsby builds :)

**Comment by mzbiejczuk** [comment]
@kjoscha Thank you! You saved me. ♥️

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or join us on [Discord](https://discord.gg/Qy2rwbHbwN) if you have questions!
