### ISSUE TITLE
Gatsby build failing if no content has been creates

### ISSUE THREAD

**Issue by vimtor** [gatsby-uc/gatsby-source-strapi#95]
Perhaps this is the intended behavior since I am not familiar with GraphQL, but when querying all the content using `allStrapi*` the build crashes instead of returning an empty array.

It's not super important but I figured out that it should be easy to fix.

**Comment by henrych4** [comment]
Related issues:
https://github.com/strapi/gatsby-source-strapi/issues/86#issuecomment-566526300
https://github.com/strapi/gatsby-source-strapi/issues/94#issuecomment-570039297

**Comment by Borisboky** [comment]
I have the same problem. How can it be fixed if it's easy to fix?

**Comment by papeloto** [comment]
I simply added some dummy data

**Comment by Borisboky** [comment]
Thanks, but that is not ideal because I have 80 content types and more than 1000 fields (there are also images). Thus if I in some case use only 50 field, I need to add some dummy data to all of them. That is too much.

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or join us on [Discord](https://discord.gg/Qy2rwbHbwN) if you have questions!
